#!/usr/bin/env bash
name="menu-cache"
version="1.1.0"
description="Caching mechanism for freedesktop.org compliant menus"
source="https://github.com/lxde/menu-cache/archive/refs/tags/$version.tar.gz"
depends="libfm-extra"
group="lxde.base"

setup(){
	cp -r ${dizin}/${paket}/files/ /tmp/kly/build/
	cd $SOURCEDIR
	patch -Np1 < ../files/menu-cache-1.1.0-0001-Support-gcc10-compilation.patch
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ 
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

