#!/usr/bin/env bash
name="libXxf86dga"
version="1.1.6"
description="X.Org Xxf86dga library"
source="https://www.x.org/archive/individual/lib/libXxf86dga-$version.tar.gz"
depends=""
group="x11.libs"


setup(){
    $SOURCEDIR/configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

