#!/bin/sh
for dir in $(ls /usr/share/icons) ; do
    if [ -d "/usr/share/icons/$dir" ] ; then

            gtk-update-icon-cache "/usr/share/icons/$dir"
     
    fi
done
    gtk-query-immodules-3.0 --update-cache
 
