#!/usr/bin/env bash
name="libXaw3d"
version="1.6.4"
description="X.Org Xaw3d library"
source="https://www.x.org/archive/individual/lib/libXaw3d-$version.tar.gz"
depends="libX11,libXt,libXmu,libXext"
group="x11.libs"


setup(){
    $SOURCEDIR/configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}
