#!/usr/bin/env bash
name="lxde-icon-theme"
version="0.5.2"
description="LXDE default icon theme based on nuoveXT2"
source="https://github.com/lxde/lxde-icon-theme/archive/refs/tags/$version.tar.gz"
depends="gtk-update-icon-cache"
builddepend="gtk3"
group="lxde.base"


setup(){
    cd $SOURCEDIR
    autoreconf -fvi
    ./configure	--prefix=/usr \
    	--libdir=/usr/lib64/  
}
build(){
    make
}

package(){
    make DESTDIR="$DESTDIR" install
}
