#!/usr/bin/env bash
name="hsakmt"
version="1.0.0"
description="Package hsakt"
source="https://www.x.org/archive/individual/lib/hsakmt-$version.tar.gz"
depends=""
group="x11.libs"


setup(){
    $SOURCEDIR/configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

