#!/usr/bin/env bash
name="libFS"
version="1.0.9"
description="X.Org FS library"
source="https://www.x.org/archive/individual/lib/libFS-$version.tar.xz"
depends="xorgproto"
group="x11.libs"


setup(){
    $SOURCEDIR/configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

