#!/usr/bin/env bash
name="libidn2"
version="2.3.8"
description="Free software implementation of IDNA2008, Punycode and TR46"
source="https://ftp.gnu.org/gnu/libidn/libidn2-${version}.tar.gz"
depends="libunistring"
group="net.dns"

setup(){
    cd $SOURCEDIR
    ./configure --prefix=/usr \
        --libdir=/usr/lib64 \
        --disable-static \
        --disable-nls
}
build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}
