#!/usr/bin/env bash
name="xcb-util-image"
version="0.4.1"
description="X C-language Bindings sample implementations"
source="https://www.x.org/releases/individual/xcb/xcb-util-image-${version}.tar.xz"
depends="libxcb,xcb-util,xorgproto,util-macros"
group="x11.libs"


setup(){
    $SOURCEDIR/configure --prefix=/usr \
        --libdir=/usr/lib64 \
	--enable-shared \
	--enable-static \
	--disable-devel-docs \
	--without-doxygen
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}
