#!/usr/bin/env bash
name="lz4"
version="1.9.4"
description="Extremely fast compression algorithm"
source="https://github.com/lz4/lz4/archive/refs/tags/v1.9.4.tar.gz"
depends=""
builddepend=""
group="app.arch"

setup(){
	echo ""
}

build(){
	cd $SOURCEDIR
    make PREFIX=/usr
}

package(){
    make install DESTDIR=$DESTDIR PREFIX=/usr
    mv ${DESTDIR}/usr/{lib,lib64}
}

