#!/usr/bin/env bash
name="libXv"
version="1.0.12"
description="X.Org Xv library"
source="https://www.x.org/archive/individual/lib/libXv-$version.tar.xz"
depends=""
group="x11.libs"


setup(){
    $SOURCEDIR/configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

