#!/usr/bin/env bash
name="alsa-utils"
version="1.2.10"
url="https://www.alsa-project.org/"
description="Advanced Linux Sound Architecture - Utilities"
source="https://github.com/alsa-project/alsa-utils/archive/refs/tags/v$version.tar.gz"
depends="pciutils,psmisc"
builddepend="alsa-lib,docbook-xsl,fftw,libsamplerate,ncurses,python3-docutils,udev,xmlto"
group="media.libs"

setup(){
	cd $SOURCEDIR
	autoreconf -fvi
	./configure --prefix=/usr \
		--libdir=/usr/lib64/ \
		--disable-alsaconf \
		--with-udev-rules-dir=/usr/lib/udev/rules.d \
		--with-systemdsystemunitdir=no
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

