#!/usr/bin/env bash
name="libXxf86vm"
version="1.1.5"
description="X.Org Xxf86vm library"
source="https://www.x.org/archive/individual/lib/libXxf86vm-$version.tar.xz"
depends=""
group="x11.libs"


setup(){
    $SOURCEDIR/configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

