#!/usr/bin/env bash
name="shared-mime-info"
version="2.4"
description="The Shared MIME-info Database specification"
source="https://gitlab.freedesktop.org/xdg/shared-mime-info/-/archive/${version}/shared-mime-info-${version}.tar.gz"
depends="libxml2"
group="x11.misc"

setup(){
	
	cd $SOURCEDIR
    meson setup $BUILDDIR --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    ninja -C $BUILDDIR
}

package(){
    DESTDIR=$DESTDIR ninja -C $BUILDDIR install
}

