#!/usr/bin/env bash
name="libepoxy"
version="1.5.10"
description="Library for handling OpenGL function pointer management"
source="https://github.com/anholt/libepoxy/archive/refs/tags/$version.tar.gz"
depends="libX11,mesa"
group="media.libs"


setup(){
	cd $SOURCEDIR
    meson setup $BUILDDIR --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    ninja -C $BUILDDIR 
}

package(){
    DESTDIR=$DESTDIR ninja -C $BUILDDIR install
}

