#!/usr/bin/env bash
name="leafpad"
version="0.8.18.1.11"
description="A notepad clone for GTK"
source="https://github.com/stevenhoneyman/l3afpad/archive/refs/tags/v${version}.tar.gz"
depends="gtk3"
group="lxde.apps"

setup(){
	cd $SOURCEDIR

    ./autogen.sh
	 ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
        --enable-chooser \
		--with-gtk=3
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

