#!/usr/bin/env bash
name="lxmenu-data"
version="0.1.6"
description="Provides files needed for LXDE application menus"
source="https://github.com/lxde/lxmenu-data/archive/refs/tags/$version.tar.gz"
depends=""
builddepend="intltool"
group="lxde.base"


setup(){
	cd $SOURCEDIR
    autoreconf -fvi
    ./configure --prefix=/usr \
        --sysconfdir=/etc
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

