#!/usr/bin/env bash
name="libgpg-error"
version="1.47"
url="https://www.gnupg.org/"
description="Support library for libgcrypt"

source="https://www.gnupg.org/ftp/gcrypt/libgpg-error/${name}-${version}.tar.bz2"
depends="glibc"
group="dev.libs"

setup(){
cd $SOURCEDIR
    autoreconf -vfi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make DESTDIR=$DESTDIR install
}

