#!/usr/bin/env bash
name="libXpresent"
version="1.0.1"
description="X Present Extension C Library"
source="https://www.x.org/archive/individual/lib/libXpresent-$version.tar.xz"
depends="libX11,xorgproto,libXext,libXfixes,libXrandr"
group="x11.libs"


setup(){
    $SOURCEDIR/configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

