#!/bin/bash
chmod 755 -R /etc/profile.d
chmod 755 -R /lib64/locale/
locale-gen
sync && sleep 1
ln -sf /usr/share/zoneinfo/Europe/Istanbul /etc/localtime
sleep 1
sed -i "/tr_TR.UTF/d" /etc/environment
echo -e "\nLANG=tr_TR.UTF-8" >> /etc/environment
sync && sleep 1
