#!/usr/bin/env bash
name="mpdecimal"
version="4.0.0"
url="https://www.bytereef.org/mpdecimal/index.html"
description="Package for correctly-rounded arbitrary precision decimal floating point arithmetic"
source="https://www.bytereef.org/software/$name/releases/$name-$version.tar.gz"
depends=""
builddepend=""
group="net.db"

setup(){
    cd $SOURCEDIR
    ./configure --prefix=/usr \
        --libdir=/usr/lib64
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

