#!/usr/bin/env bash
name="gdbm"
version="1.23"
description="GNU dbm is a set of database routines that use extensible hashing"
source="https://ftp.gnu.org/gnu/gdbm/gdbm-$version.tar.gz"
depends=""
builddepend=""
group="dev.libs"

setup(){
	cd $SOURCEDIR
    ./configure --prefix=/usr \
    	--libdir=/usr/lib64 \
		--enable-libgdbm-compat \
		--disable-largefile \
		--disable-dependency-tracking \
		--enable-fast-install
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

