#!/usr/bin/env bash
name="at-spi2-core"

version="2.50.1"
url="https://gitlab.gnome.org/GNOME/at-spi2-core"
description="GTK+ & GNOME Accessibility Toolkit"

source="https://gitlab.gnome.org/GNOME/at-spi2-core/-/archive/AT_SPI2_CORE_${version//./_}/at-spi2-core-AT_SPI2_CORE_${version//./_}.tar.gz"
depends="glib,libffi,libpcre2,libXtst"

setup(){
cd $SOURCEDIR
    meson setup $BUILDDIR --prefix=/usr \
        --libdir=/usr/lib64/ 

}

build(){
    ninja -C $BUILDDIR
}

package(){
   DESTDIR=$DESTDIR ninja -C $BUILDDIR install
}

