#!/usr/bin/env bash
name="hicolor-icon-theme"
version="0.17"
description="Freedesktop.org Hicolor icon theme"
source="http://icon-theme.freedesktop.org/releases/hicolor-icon-theme-$version.tar.xz"
depends=""
group="x11.themes"


setup(){
    cd $SOURCEDIR
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

