#!/usr/bin/env bash
name="lxterminal"
version="0.4.1"
description="Lightweight vte-based tabbed terminal emulator for LXDE"
#source="https://salsa.debian.org/lxde-team/lxterminal/-/archive/debian/$version-2/lxterminal-debian-$version-2.tar.gz"
source="https://github.com/lxde/lxterminal/archive/refs/tags/$version.tar.gz"	
depends="vte3,gtk3,dejavu"
builddepend="intltool"
group="lxde.base"


setup(){
	cd $SOURCEDIR
	autoreconf -fvi
    ./configure \
    	--prefix=/usr \
        --libdir=/usr/lib64/ \
        --enable-gtk3 
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

