#!/usr/bin/env bash
name="libdmx"
version="1.1.4"
description="X.Org dmx library"
source="https://www.x.org/archive/individual/lib/libdmx-$version.tar.gz"
depends=""
group="x11.libs"


setup(){
    $SOURCEDIR/configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

