#!/usr/bin/env bash
name="lxappearance"
version="0.6.4"
description="Feature-rich GTK+ theme switcher of the LXDE Desktop"
#source="https://downloads.sourceforge.net/lxde/$name-$version.tar.xz"
source="https://github.com/lxde/lxappearance/archive/refs/tags/$version.tar.gz"
depends="gtk3,dbus-glib"
builddepend=""
group="lxde.base"

setup(){
	cp -prf ${dizin}/${paket}/files/ /tmp/kly/build/
	cd $SOURCEDIR
	patch -Np1 -i ../files/00-gtk3-fix.patch
	autoreconf -fvi
	./configure --prefix=/usr \
		--enable-gtk3 \
		--libdir=/usr/lib64/ \
		--enable-dbus
        
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

