#!/usr/bin/env bash
name="gtksourceview4"
version="4.8.4"
description="A text widget adding syntax highlighting and more to GNOME"
source="https://download.gnome.org/sources/gtksourceview/${version%.*}/gtksourceview-${version}.tar.xz"
depends="gtk3,libxml2,gobject-introspection"
group="x11.libs"


setup(){
	cd $SOURCEDIR
    meson setup $BUILDDIR --prefix=/usr \
        --libdir=/usr/lib64/ \
        -Db_lto=true \
        -Dgtk_doc=true
}

build(){
    ninja -C $BUILDDIR
}

package(){
    DESTDIR=$DESTDIR ninja -C $BUILDDIR install
}

