#!/usr/bin/env bash
name="libxkbui"
version="1.0.2"
description="Package libxkbui"
source="https://www.x.org/archive/individual/lib/libxkbui-$version.tar.gz"
depends="libX11,libXt,libxkbfile"
group="x11.libs"


setup(){
    $SOURCEDIR/configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

